import { async } from '@firebase/util';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import Head from 'next/head'
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Message from '../components/MessageComponent/Message'
import { DB } from '../utilities/firebaseConfigs';

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(DB, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    const unsubscribe = onSnapshot(q, (snap) => {
      setAllPosts(snap.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  }

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-8 text-lg font-medium'>
        <h2>See what athor people are saying</h2>
        {allPosts.map((post) => {
          return (<Message {...post} key={post.id}>
            <Link href={`/${post.id}`}>
              <button>{post.comments?.length ?? 0} Comments</button>
            </Link>
          </Message>)
        })}
      </div>

    </div>
  )

}
